{% set name = "dwave-neal" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dwavesystems/dwave-neal/archive/refs/tags/{{ version }}.tar.gz
  sha256: 410344e750ca0525cbd89df511e6c992afc2f21c08165b9faa510df304a3da81

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - setuptools >=46.4.0
    - wheel
    - pip
    - python
  run:
    - dwave-samplers >=1.0.0,<2.0.0
    - python

test:
  imports:
    - neal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-neal
  summary: General Ising graph simulated annealing solver
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
