{% set name = "dwave-neal" %}
{% set version = "0.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-neal-{{ version }}.tar.gz
  sha256: 6eabf37a7ccbed7f6145567351673a07f9ba5482a2500872c840b27089e0ff3e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy 1.20                             # [build_platform != target_platform and py<310]
    - numpy                                  # [build_platform != target_platform and py>=310]
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - numpy 1.20  # [py<310]
    - numpy       # [py>=310]
    - setuptools >=46.4.0
    - wheel
    - pip
    - python
  run:
    - dimod >=0.9.11
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - neal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-neal
  summary: General Ising graph simulated annealing solver
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
